### ISSUE TITLE
Create Class Diagram

### ISSUE THREAD

**Issue by eutkan** [bounswe/bounswe2018group10#48]
Preparing class diagram as one of the group of 4 people.

**Comment by abdusco** [comment]
I'll append the current progress here:

```yaml
Projects:
  create(Project $project): Boolean
  get(Integer $id): Project
  find($options[]): Project[]
  findOne($options[]): Project
  update(Project $p): Boolean
  delete(Project $p): Boolean
  all(): Project[]
  
Project:
  # PROPERTIES
  name: String
  body: String
    - HTML
  isCompleted: Boolean
  isActive: Boolean
  isModified: Boolean

  created: DateTime
  modified: DateTime
  deadline: DateTime
  
  creator: RegisteredUser[]
    - could also be Client[]
  bidders: RegisteredUser[]
    - could also be Freelancer[]

  budget: Int[]
    - a range of values
  bids: Bid[]
  ratings: Rating[]
    - force client to rate the project
  comments: Comment[]
  messages: Messages
    - for the messages between the client and the freelancer
  annotations: Annotation[]
  tags: Tag[]
  files: File[]

  # METHODS
  setBudget(Integer[] $range): Boolean
  bid(Bid $bid): Bid
  rate(Rating $rating): Boolean
  annotate(Annotation $annotation): Annotation
  complete(): Boolean
    - redirect to project rating page
  acceptBid(Bid $bid): Boolean
  
Search:
  query: String
  
Users:
  create(User $user): Boolean
  get(Integer $id): Project
  find($options[]): Project[]
  findOne($options[]): Project
  update(RegisteredUser $p): Boolean
  delete(RegisteredUser $p): Boolean
  all(): RegisteredUser[]
  verify(User $user): Boolean
  
User: 
  
RegisteredUser:
  name: String
  displayName: String
  # pass: String
  email: String
  profiles: Profile[]
  conversations: Conversation[]

  # METHODS
  setPassword(String $pass): Boolean
  
Profiles:
  # METHODS
  create(Profile $profile): Boolean
  get(Integer $id): Profile
  find($options[]): Profile[]
  findOne($options[]): Profile
  update(Profile $p): Boolean
  delete(Profile $p): Boolean
  all(): Profile[]
  
  
Profile:
  # PROPERTIES
  name: String
  avatar: String (url)
  body: String (html)
  ratings: Rating[]
  comments: Comment[]
  files: File[]
  annotations: Annotation[]
  favorites: Project[]
    - push/pop/shift/unshift methods by default for all arrays
  savedSearches: Search[]
  
  # METHODS
  addComment(Comment $comment): Comment
  addRating(Rating $rating): Rating
  addAnnotation(Annotation $annotation): Annotation
  
  
Session:
  # PROPERTIES
  user: User

  # METHODS
  login($username, $pass): RegisteredUser
  logout(): Boolean
  redirect($url): void
  loginSocial(): void
  
Bid:
  amount: Int
    - in cents
  isActive: Boolean
  user: RegisteredUser
  created: DateTime
  modified: DateTime
  
  
Rating:
  user: RegisteredUser
  type: String
  rating: Int
  
Comment:
  user: RegisteredUser
  created: DateTime
  modified: DateTime
  isActive: Boolean
  body: String
  
Payment:
  created: DateTime
  user: RegisteredUser
  recipient: RegisteredUser
  isWithdrawn: Boolean
    - to denote when the advance payment is paid by the client
  isCompleted: Boolean
  report: File[]
  
Annotation:
  user: RegisteredUser
  created: DateTime
  modified: DateTime
  title: String
  color: Color
    - out of some options
    
  Conversation:
  # PROPERTIES
  project: Project
  participants: RegisteredUser[]
  created: DateTime
  isActive: Boolean

  messages: Message[]

  # METHODS
  post(Message $message): Message
  remove(Message $message): Boolean
  close(): Boolean
  
Message:
  # PROPERTIES
  sender: RegisteredUser
  recipient: RegisteredUser
  created: DateTime
  # modified: DateTime
  # isModified: Boolean
  # isRead: Boolean
  body: String
  files: File[]
  repliedTo: Message/null

  # METHODS
  postTo(Conversation $conversation): Message
  delete(): Boolean


MessageListener:
  onMessagePosted(Message $message){}
```
